apiVersion: v2
name: ansible-operator
description: An opinionated runner for Ansible on Kubernetes
type: application
version: 0.0.7 # VERSION
appVersion: "0.0.7"
dependencies:
  - name: crds
    version: 0.0.7 # VERSION
    condition: crds.install
