apiVersion: v2
name: ansible-operator
description: An opinionated runner for Ansible on Kubernetes
type: application
version: 0.1.0 # VERSION
appVersion: "0.1.0"
dependencies:
  - name: crds
    version: 0.1.0 # VERSION
    condition: crds.install
